Gitlab support
fxpio/tug pull request #1
Opened 2018-08-23 10:11 UTC by Swahjak

First off; Awesome job on this satis implementation. Have been struggling with Satis for way to long and this solves everything that is wrong with the 'default' satis implementation.

I have been following along since I first encountered this repository and created a branch to support Gitlab. Thought you might be interested in checking it out and possibly merging it.

2018-09-03 17:32 UTC, francoispluchino requested changes
Thank you for your message and your PR. I could not answer you before, because I was in vacation in a place where I did not have any network connection ... It is always a pleasure to see my work being appreciated and used. Add support to Gitlab is something I wanted to do, so thanks for your help (just like the support for native GIT). However, I have some requests before merging your PR:

- Rebase your PR into 1 commit
- Fix your tests

2018-09-03 17:39 UTC, francoispluchino requested changes
Thanks to make changes of your code for comments on each line :-).

2018-09-03 17:39 UTC, francoispluchino commented on aws/cloud-formation-stack.yaml
> -
Remove this empty line

2018-09-03 17:39 UTC, francoispluchino commented on src/composer/repositories/VcsRepository.ts
> -        this.repoData['type'] = 'vcs-' + validType;
Do not delete these 2 lines.

2018-09-03 17:39 UTC, francoispluchino commented on src/composer/repositories/vcs-drivers/GitlabDriver.ts
> + * @author François Pluchino <francois.pluchino@gmail.com>
Replace by your full name and email, it's your work :-).

2018-09-03 17:39 UTC, francoispluchino commented on src/configs/Config.ts
> -        'github-domains': ['github.com'],
Do not delete this line.

2018-09-13 13:39 UTC, Swahjak commented
@francoispluchino No problem. I will try to look into it in the upcoming week.

2018-10-17 10:01 UTC, Swahjak commented
@francoispluchino I'm sorry haven't got to it before my holidays. I will try to make time next week.

2020-05-09 17:44 UTC, francoispluchino commented
@Swahjak Thank you for your contribution, however, your PR was still awaiting modifications, and in the meantime, a lot of changes have taken place to arrive at the first stable version. Therefore, your PR is in conflict, and I so added personally this new functionality via the commit d85390b34fc058aa820ee7c6cbb058bf061cdb32.

2020-05-09 17:44 UTC, closed without merging

2020-05-10 10:02 UTC, Swahjak commented
@francoispluchino I can only applaud that :clap: